name: 'Test gh-access'

on:
  push:
    branches:
    pull_request:
    tags:

jobs:
  generate_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            action_shell: bash
            python_version: '3.11'
            curl_cmd: curl

          - os: macos-latest
            action_shell: bash
            python_version: '3.11'
            curl_cmd: curl

          - os: windows-latest
            action_shell: powershell
            python_version: '3.11'
            curl_cmd: "cmd.exe /c curl"

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Generate token !'
        id: accessToken
        uses: dolby-io-internal/gh-access@main
        with:
          gh_app_priv_key: ${{ secrets.PEM_B64 }}
          gh_app_id: ${{ secrets.GH_APP_ID }}
          gh_app_installation_id: ${{ secrets.GH_APP_INSTALLATION_ID }}
          action_shell: ${{ matrix.action_shell }}

      - name: 'Check access token - ${{ matrix.os }}'
        run: ./tests.py
        env:
          ACCESS_TOKEN: ${{ steps.accessToken.outputs.token }}

      - name: 'Use access token to list releases.'
        run: |
          ${{ matrix.curl_cmd }} -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.accessToken.outputs.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/dolby-io-internal/gh-access/releases
